# Generated by Django 4.2.7 on 2023-12-02 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petListings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petlisting',
            old_name='colour',
            new_name='description',
        ),
    ]
