# Generated by Django 4.2.7 on 2023-11-11 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('petListings', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('living_situation', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo')], max_length=255)),
                ('ownership', models.CharField(choices=[('own', 'Own'), ('rent', 'Rent')], max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('number_of_pets', models.PositiveIntegerField()),
                ('exercise_hours', models.PositiveIntegerField()),
                ('alone_hours', models.PositiveIntegerField()),
                ('adoption_reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('available', 'Available'), ('adopted', 'Adopted'), ('pending', 'Pending'), ('withdrawn', 'Withdrawn')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petListings.petlisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
