
# Generated by Django 4.2.7 on 2023-11-15 05:56


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='living_situation',
            field=models.CharField(choices=[('house', 'house'), ('apartment', 'apartment'), ('condo', 'condo')], max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='ownership',
            field=models.CharField(choices=[('own', 'own'), ('rent', 'rent')], max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('denied', 'denied'), ('pending', 'pending'), ('withdrawn', 'withdrawn')], default='pending', max_length=255),
        ),
    ]
